/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Gpio */

#ifndef _Included_Gpio
#define _Included_Gpio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Gpio
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_raspio_Gpio_open
  (JNIEnv *, jobject, jint);

/*
 * Class:     Gpio
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_raspio_Gpio_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     Gpio
 * Method:    setDirection
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_raspio_Gpio_setDirection
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Gpio
 * Method:    getValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_raspio_Gpio_getValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     Gpio
 * Method:    setValue
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_raspio_Gpio_setValue
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
