/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Uart */

#ifndef _Included_Uart
#define _Included_Uart
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Uart
 * Method:    open
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_raspio_Uart_open
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Uart
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_raspio_Uart_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     Uart
 * Method:    read
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_example_raspio_Uart_read
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     Uart
 * Method:    write
 * Signature: (I[BI)V
 */
JNIEXPORT void JNICALL Java_com_example_raspio_Uart_write
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     Uart
 * Method:    isDataAvailable
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_raspio_Uart_isDataAvailable
  (JNIEnv *, jobject, jint);

/*
 * Class:     Uart
 * Method:    flush
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_raspio_Uart_flush
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
